"""Resolve hub tool source text (thin adapter vs noun implementation)."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ADAPTER_TO_NOUN: dict[str, str] = {
    "tools/apply-charter-corpus-pointer.py": "charter_corpus_pointer",
    "tools/assert-adjective-locality-violation-fails.py": "assert_adjective_locality_violation_fails",
    "tools/assert-adopter-verify-fast-green-passes.py": "assert_adopter_verify_fast_green_passes",
    "tools/assert-agent-noun-structure-passes.py": "assert_agent_noun_structure_passes",
    "tools/assert-batch-generate-policy-fails.py": "assert_batch_generate_policy_fails",
    "tools/assert-binding-matrix-met.py": "assert_binding_matrix_met",
    "tools/assert-boundary-io-fails.py": "assert_boundary_io_fails",
    "tools/assert-brownfield-inventory-passes.py": "assert_brownfield_inventory_passes",
    "tools/assert-c1-fails.py": "assert_c1_fails",
    "tools/assert-c1-no-note-fails.py": "assert_c1_no_note_fails",
    "tools/assert-c1-wrong-class-fails.py": "assert_c1_wrong_class_fails",
    "tools/assert-c10-breaking-fails.py": "assert_c10_breaking_fails",
    "tools/assert-c10-changed-scoped-passes.py": "assert_c10_changed_scoped_passes",
    "tools/assert-c10-fails.py": "assert_c10_fails",
    "tools/assert-c13-fails.py": "assert_c13_fails",
    "tools/assert-c15-fails.py": "assert_c15_fails",
    "tools/assert-c15-key-fails.py": "assert_c15_key_fails",
    "tools/assert-c15-nested-fails.py": "assert_c15_nested_fails",
    "tools/assert-c15-unused-fails.py": "assert_c15_unused_fails",
    "tools/assert-c16-fails.py": "assert_c16_fails",
    "tools/assert-c17-fails.py": "assert_c17_fails",
    "tools/assert-c17-no-failure-fails.py": "assert_c17_no_failure_fails",
    "tools/assert-c17-no-preserve-fails.py": "assert_c17_no_preserve_fails",
    "tools/assert-c18-fails.py": "assert_c18_fails",
    "tools/assert-c18-missing-fails.py": "assert_c18_missing_fails",
    "tools/assert-c18-no-call-fails.py": "assert_c18_no_call_fails",
    "tools/assert-c2-fails.py": "assert_c2_fails",
    "tools/assert-c21-changed-scoped-passes.py": "assert_c21_changed_scoped_passes",
    "tools/assert-c21-fails.py": "assert_c21_fails",
    "tools/assert-c22-fails.py": "assert_c22_fails",
    "tools/assert-c22-na-fails.py": "assert_c22_na_fails",
    "tools/assert-c23-confirm-fails.py": "assert_c23_confirm_fails",
    "tools/assert-c23-fails.py": "assert_c23_fails",
    "tools/assert-c24-agent-fails.py": "assert_c24_agent_fails",
    "tools/assert-c24-fails.py": "assert_c24_fails",
    "tools/assert-c3-fails.py": "assert_c3_fails",
    "tools/assert-call-tree-pack-reference-passes.py": "assert_call_tree_pack_reference_passes",
    "tools/assert-changed-missing-fails.py": "assert_changed_missing_fails",
    "tools/assert-contract-change-detects-c21-fails.py": "assert_contract_change_detects_c21_fails",
    "tools/assert-contract-presence-fails.py": "assert_contract_presence_fails",
    "tools/assert-dashboard-interview-passes.py": "assert_dashboard_interview_passes",
    "tools/assert-delta-regen-narrow-passes.py": "assert_delta_regen_narrow_passes",
    "tools/assert-duplicated-adjective-fails.py": "assert_duplicated_adjective_fails",
    "tools/assert-durable-engine-rule-fails.py": "assert_durable_engine_rule_fails",
    "tools/assert-emit-audit-fails.py": "assert_emit_audit_fails",
    "tools/assert-escape-hatch-violation-fails.py": "assert_escape_hatch_violation_fails",
    "tools/assert-full-nlc-audit-emit-checklist-passes.py": "assert_full_nlc_audit_emit_checklist_passes",
    "tools/assert-full-nlc-audit-quick-passes.py": "assert_full_nlc_audit_quick_passes",
    "tools/assert-gate-record-describe-passes.py": "assert_gate_record_describe_passes",
    "tools/assert-goal-bindings-narrow-fails.py": "assert_goal_bindings_narrow_fails",
    "tools/assert-goal-scaffold-emits-markers.py": "assert_goal_scaffold_emits_markers",
    "tools/assert-guide-orchestration-passes.py": "assert_guide_orchestration_passes",
    "tools/assert-hub-no-product-requirements-passes.py": "assert_hub_no_product_requirements_passes",
    "tools/assert-hub-rule-coverage-passes.py": "assert_hub_rule_coverage_passes",
    "tools/assert-human-surface-passes.py": "assert_human_surface_passes",
    "tools/assert-impact-graph-generated.py": "assert_impact_graph_generated",
    "tools/assert-install-verify-passes.py": "assert_install_verify_passes",
    "tools/assert-interview-gap-passes.py": "assert_interview_gap_passes",
    "tools/assert-interview-packet-fails.py": "assert_interview_packet_fails",
    "tools/assert-invoice-correct-contract-blockers-passes.py": "assert_invoice_correct_contract_blockers_passes",
    "tools/assert-invoice-correct-noun-inheritance-passes.py": "assert_invoice_correct_noun_inheritance_passes",
    "tools/assert-invoice-violation-fails.py": "assert_invoice_violation_fails",
    "tools/assert-migration-catalog-passes.py": "assert_migration_catalog_passes",
    "tools/assert-migration-step-noop-passes.py": "assert_migration_step_noop_passes",
    "tools/assert-nlc-naming-passes.py": "assert_nlc_naming_passes",
    "tools/assert-nlc-update-hermetic-passes.py": "assert_nlc_update_hermetic_passes",
    "tools/assert-non-python-adapter-fails.py": "assert_non_python_adapter_fails",
    "tools/assert-non-python-adapter-passes.py": "assert_non_python_adapter_passes",
    "tools/assert-noun-inheritance-fails.py": "assert_noun_inheritance_fails",
    "tools/assert-p2-hub-scope-passes.py": "assert_p2_hub_scope_passes",
    "tools/assert-pack-ingest-candidates-passes.py": "assert_pack_ingest_candidates_passes",
    "tools/assert-produce-handoff-refused.py": "assert_produce_handoff_refused",
    "tools/assert-produce-role-separation-refused.py": "assert_produce_role_separation_refused",
    "tools/assert-project-lock-schema-passes.py": "assert_project_lock_schema_passes",
    "tools/assert-quality-metric-passes.py": "assert_quality_metric_passes",
    "tools/assert-r12-fails.py": "assert_r12_fails",
    "tools/assert-r13-fails.py": "assert_r13_fails",
    "tools/assert-r15-fails.py": "assert_r15_fails",
    "tools/assert-r15-import-fails.py": "assert_r15_import_fails",
    "tools/assert-r17-fails.py": "assert_r17_fails",
    "tools/assert-r18-fails.py": "assert_r18_fails",
    "tools/assert-r20-fails.py": "assert_r20_fails",
    "tools/assert-r20-type-fails.py": "assert_r20_type_fails",
    "tools/assert-r20-unannotated-fails.py": "assert_r20_unannotated_fails",
    "tools/assert-r25-fails.py": "assert_r25_fails",
    "tools/assert-r4-fails.py": "assert_r4_fails",
    "tools/assert-r4-mention-fails.py": "assert_r4_mention_fails",
    "tools/assert-rca-packet-blame-fails.py": "assert_rca_packet_blame_fails",
    "tools/assert-release-preflight-passes.py": "assert_release_preflight_passes",
    "tools/assert-release-signed-passes.py": "assert_release_signed_passes",
    "tools/assert-release-smoke-passes.py": "assert_release_smoke_passes",
    "tools/assert-release-tag-gate-fails.py": "assert_release_tag_gate_fails",
    "tools/assert-release-unsigned-fails.py": "assert_release_unsigned_fails",
    "tools/assert-requirements-hub-entrypoints-passes.py": "assert_requirements_hub_entrypoints_passes",
    "tools/assert-requirements-sync-pending-fails.py": "assert_requirements_sync_pending_fails",
    "tools/assert-rule-adoption-conflicts-fails.py": "assert_rule_adoption_conflicts_fails",
    "tools/assert-rule-adoption-passes.py": "assert_rule_adoption_passes",
    "tools/assert-rule-coverage-fails.py": "assert_rule_coverage_fails",
    "tools/assert-rule-coverage-passes.py": "assert_rule_coverage_passes",
    "tools/assert-rule-emit-sync-passes.py": "assert_rule_emit_sync_passes",
    "tools/assert-rule-marker-emit.py": "assert_rule_marker_emit",
    "tools/assert-rule-runner-fails.py": "assert_rule_runner_fails",
    "tools/assert-rule-runner-passes.py": "assert_rule_runner_passes",
    "tools/assert-schema-identity-fails.py": "assert_schema_identity_fails",
    "tools/assert-shipped-tag-audit-fails.py": "assert_shipped_tag_audit_fails",
    "tools/assert-sql-escape-fails.py": "assert_sql_escape_fails",
    "tools/assert-taint-alias-fails.py": "assert_taint_alias_fails",
    "tools/assert-taint-crossfile-fails.py": "assert_taint_crossfile_fails",
    "tools/assert-taint-helper-fails.py": "assert_taint_helper_fails",
    "tools/assert-taint-violation-fails.py": "assert_taint_violation_fails",
    "tools/assert-todo-use-cases-ssot-fails.py": "assert_todo_use_cases_ssot_fails",
    "tools/assert-upstream-hand-patch-fails.py": "assert_upstream_hand_patch_fails",
    "tools/assert-validate-agent-nouns-passes.py": "assert_validate_agent_nouns_passes",
    "tools/assert-verb-path-violation-fails.py": "assert_verb_path_violation_fails",
    "tools/assert-verify-before-generate-stamp-fails.py": "assert_verify_before_generate_stamp_fails",
    "tools/assert-verify-breaking-accept-fails.py": "assert_verify_breaking_accept_fails",
    "tools/assert-verify-contract-change-fails.py": "assert_verify_contract_change_fails",
    "tools/assert-verify-deep-produce-refused.py": "assert_verify_deep_produce_refused",
    "tools/assert-verify-deep-role-separation-refused.py": "assert_verify_deep_role_separation_refused",
    "tools/assert-verify-gate-record-fails.py": "assert_verify_gate_record_fails",
    "tools/assert-verify-regen-queue-fails.py": "assert_verify_regen_queue_fails",
    "tools/assert-verify-rule-coverage-blockers-fails.py": "assert_verify_rule_coverage_blockers_fails",
    "tools/assert-verify-rule-coverage-blockers-passes.py": "assert_verify_rule_coverage_blockers_passes",
    "tools/assert-verify-rule-marker-gate-fails.py": "assert_verify_rule_marker_gate_fails",
    "tools/assert-verify-skill-gate-fails.py": "assert_verify_skill_gate_fails",
    "tools/assert-verify-stale-stamp-fails.py": "assert_verify_stale_stamp_fails",
    "tools/changeset.py": "changeset",
    "tools/check-rule-adoption.py": "check_rule_adoption",
    "tools/ci_fitness.py": "ci_fitness",
    "tools/generate-impact-graph.py": "generate_impact_graph",
    "tools/link-terms-dictionary.py": "link_terms_dictionary",
    "tools/load-knowledge-domain.py": "load_knowledge_domain",
    "tools/markdown_plain.py": "markdown_plain",
    "tools/nlc-action-gates.py": "action_gates",
    "tools/nlc-action-plan-gate.py": "action_plan_gate",
    "tools/nlc-adr-active-freshness.py": "adr_active_freshness",
    "tools/nlc-adr-bind-snapshot.py": "adr_bind_snapshot",
    "tools/nlc-adr-lineage-check.py": "adr_lineage_check",
    "tools/nlc-brownfield-inventory.py": "brownfield_inventory",
    "tools/nlc-brownfield-migrate.py": "brownfield_migrate",
    "tools/nlc-delta-regen.py": "delta_regen",
    "tools/nlc-emit-manifest-enforce.py": "emit_manifest_enforce",
    "tools/nlc-fetch-hub.py": "fetch_hub",
    "tools/nlc-impact-graph.py": "impact_graph",
    "tools/nlc-install-hash-update.py": "install_hash_update",
    "tools/nlc-install-verify.py": "install_verify",
    "tools/nlc-pack-export.py": "pack_export",
    "tools/nlc-pack-install.py": "pack_install",
    "tools/nlc-release-build.py": "release_build",
    "tools/nlc-reverse-audit.py": "reverse_audit",
    "tools/nlc-update.py": "hub_update",
    "tools/nlc.py": "nlc_hub_cli",
    "tools/nlc_adr_active.py": "adr_active",
    "tools/nlc_adr_scan.py": "adr_scan",
    "tools/nlc_call_tree.py": "call_tree",
    "tools/nlc_cli_help.py": "cli_help",
    "tools/nlc_compliance.py": "compliance",
    "tools/nlc_contract_break_accept.py": "contract_break_accept",
    "tools/nlc_contract_change.py": "contract_change",
    "tools/nlc_dashboard.py": "dashboard",
    "tools/nlc_distribution.py": "distribution",
    "tools/nlc_emit_audit.py": "emit_audit",
    "tools/nlc_gate_record.py": "gate_ledger",
    "tools/nlc_gate_scope.py": "gate_ledger",
    "tools/nlc_generate_provenance.py": "generate_provenance",
    "tools/nlc_guide_cmd.py": "guide_cmd",
    "tools/nlc_guide_state.py": "guide_state",
    "tools/nlc_human_gap.py": "human_gap",
    "tools/nlc_language_scan.py": "language_scan",
    "tools/nlc_lock_validate.py": "lock_validate",
    "tools/nlc_menu_data.py": "menu_data",
    "tools/nlc_migration_catalog.py": "migration_catalog",
    "tools/nlc_pipeline.py": "pipeline",
    "tools/nlc_plan_audit.py": "plan_audit",
    "tools/nlc_preflight.py": "preflight",
    "tools/nlc_primitive_propose.py": "primitive_propose",
    "tools/nlc_produce_package.py": "produce_package",
    "tools/nlc_regen_continue.py": "regen_continue",
    "tools/nlc_release_bump.py": "release_bump",
    "tools/nlc_release_notes.py": "release_notes",
    "tools/nlc_release_preflight.py": "release_preflight",
    "tools/nlc_release_tags.py": "release_tags",
    "tools/nlc_release_target_preflight.py": "release_target_preflight",
    "tools/nlc_requirements.py": "requirements",
    "tools/nlc_requirements_cmd.py": "requirements_cmd",
    "tools/nlc_rule_coverage.py": "rule_receipt",
    "tools/nlc_rule_emit.py": "rule_receipt",
    "tools/nlc_rule_marker.py": "rule_receipt",
    "tools/nlc_rule_runner.py": "rule_receipt",
    "tools/nlc_todo_ssot.py": "todo_ssot",
    "tools/nlc_uc9_bindings.py": "uc9_bindings",
    "tools/nlc_uc_blockers.py": "uc_blockers",
    "tools/nlc_verify.py": "verify",
    "tools/product_tree.py": "product_tree",
    "tools/release-audit.py": "release_audit",
    "tools/validate-agent-noun-packages.py": "validate_agent_noun_packages",
    "tools/validate-interview-packet.py": "interview_packet",
    "tools/validate-knowledge-facts.py": "knowledge_facts",
    "tools/validate-pack-ingest-candidates.py": "pack_ingest_candidates",
}


def read_tool(rel: str, noun: str | None = None) -> str:
    """Return implementation text for fitness string checks."""
    rel_norm = rel.replace("\\", "/")
    adapter = ROOT / rel_norm
    if not adapter.is_file():
        return ""
    text = adapter.read_text(encoding="utf-8", errors="replace")
    slug = noun or ADAPTER_TO_NOUN.get(rel_norm)
    if not slug and rel_norm.startswith("tools/fitness-") and adapter.name.endswith(".py"):
        slug = adapter.stem.replace("-", "_")
    if not slug:
        return text
    noun_path = ROOT / "tools" / "nouns" / slug / f"{slug}.py"
    if not noun_path.is_file():
        return text
    if len(text) < 2000 and (f"nouns.{slug}" in text or "import *" in text):
        return noun_path.read_text(encoding="utf-8", errors="replace")
    if f"nouns.{slug}" in text:
        return text + "\n" + noun_path.read_text(encoding="utf-8", errors="replace")
    return text
